let places = ["China", "UK", "USA", "Canada", "France"];
let originalArr = ["China", "UK", "USA", "Canada", "France"];
console.log("Original Order: " + places);
console.log("Alphabetic Order: " + places.sort());
console.log("Original Order: " + originalArr);
console.log("Reverse Alphabetic Order: " + places.reverse());
console.log("Original Order: " + originalArr);
console.log("Reverse Order: " + originalArr.reverse());
console.log("Reverse Original Order: " + originalArr.reverse());
console.log("Alphabetic Order: " + originalArr.sort());
console.log("Reverse Alphabetic Order: " + originalArr.reverse());
